# Generated by Django 5.2.7 on 2025-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
